# Generated by Django 5.0.4 on 2024-05-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitems',
            name='order',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('disabled', 'Disabled'), ('draft', 'Draft'), ('in_review', 'In_review')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(5, '★★★★★'), (3, '★★★☆☆'), (1, '★☆☆☆☆'), (4, '★★★★☆'), (2, '★★☆☆☆')], default=None),
        ),
        migrations.DeleteModel(
            name='CartOrder',
        ),
    ]
