# Generated by Django 5.0.4 on 2024-05-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_cartorderitems_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('rejected', 'Rejected'), ('draft', 'Draft'), ('in_review', 'In_review')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(2, '★★☆☆☆'), (5, '★★★★★'), (4, '★★★★☆'), (1, '★☆☆☆☆'), (3, '★★★☆☆')], default=None),
        ),
    ]
